---
- hosts: webservers
  become: true
  tasks:
  - name: Installation of packages on Redhat family
    when: ansible_os_family = "Redhat"
    yum: path={{item}} state=present
    with_items:
    - vim
    - zip
    - curl
    - nginx

  - name: Installation of packages on Debain family
    when: ansible_os_family = "Debain"
    apt: path={{item}} state=present
    with_items:
    - vim
    - zip
    - curl
    - nginx
   
